// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1mfSgKmsqmgYEMx7M1fqWOi-n_VXm1w',
    appId: '1:133760645670:web:0b9ebe58197898e6e204e7',
    messagingSenderId: '133760645670',
    projectId: 'e-commerce-app-c96c1',
    authDomain: 'e-commerce-app-c96c1.firebaseapp.com',
    storageBucket: 'e-commerce-app-c96c1.firebasestorage.app',
    measurementId: 'G-9CJF3H6GPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByr2BhFEQa9knuDP1xyIxmEafncgPgxE0',
    appId: '1:133760645670:android:5648debb9a67b566e204e7',
    messagingSenderId: '133760645670',
    projectId: 'e-commerce-app-c96c1',
    storageBucket: 'e-commerce-app-c96c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR2JCwevW9mjs73ChlBpHPtp-VY4dMA5g',
    appId: '1:133760645670:ios:07b02e7fd0e63154e204e7',
    messagingSenderId: '133760645670',
    projectId: 'e-commerce-app-c96c1',
    storageBucket: 'e-commerce-app-c96c1.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR2JCwevW9mjs73ChlBpHPtp-VY4dMA5g',
    appId: '1:133760645670:ios:07b02e7fd0e63154e204e7',
    messagingSenderId: '133760645670',
    projectId: 'e-commerce-app-c96c1',
    storageBucket: 'e-commerce-app-c96c1.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV1mfSgKmsqmgYEMx7M1fqWOi-n_VXm1w',
    appId: '1:133760645670:web:eb7691eeab042e12e204e7',
    messagingSenderId: '133760645670',
    projectId: 'e-commerce-app-c96c1',
    authDomain: 'e-commerce-app-c96c1.firebaseapp.com',
    storageBucket: 'e-commerce-app-c96c1.firebasestorage.app',
    measurementId: 'G-HY0HXD1JQH',
  );
}
